# Generated by Django 4.1.2 on 2022-10-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('address', models.CharField(max_length=30, verbose_name='Dirección')),
                ('email', models.CharField(max_length=30, verbose_name='Correo')),
                ('favorite_food', models.CharField(max_length=50, verbose_name='Comida favorita')),
            ],
        ),
    ]
